





# sentiment_analysis:
#   description: >
#     Analyse the sentiment of user input and provide insights based on the analysis.
#   expected_output: >
#     A summary of the sentiment analysis.
#   agent: sentiment_analyser


conversation:
  description: >
    Engage in the friendly conversation with the user and respond to the user. Use the records in the journal.txt file as context sometimes in the cnoversation.
    Use some emojis here and there to make the conversation more engaging. Till the use says bye or stop something similar continue the conversation.
    The user input is {user_input} and the journal records are stored in journal.txt.
  expected_output: >
    A meaningful conversation with the user.
  agent: conversation_agent
  

# reflection:
#   description: >
#     Provide insights and reflections on user input and conversations back to the user.
#     Give constructive feedback and suggestions based on the analysis to the user in a simple manner.
#   expected_output: >
#     A summary of insights and reflections on user input and conversations.
#   agent: reflection_agent

